apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  namespace: signalpet
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

